{* @version    $Id: template.phtml 2 2009-07-13 20:58:52Z david@grudl.com $
 * @param Paginator $paginator
 * @param array     $steps
 *}
<nav n:if="$paginator->pageCount > 1">
  <ul class="pagination">
	{if $paginator->isFirst()}
    <li class="disabled">
      <span>
        <span aria-hidden="true">&laquo; Predošlá</span>
      </span>
    </li>
	{else}
    <li>
      <a href="{link this, 'page' => $paginator->page - 1}"><span aria-hidden="true">&laquo; Predošlá</span></a>
    </li>
	{/if}

	{foreach $steps as $step}
	{if $step == $paginator->page}
    <li class="active">
      <span>{$step} <span class="sr-only">(aktuálna)</span></span>
    </li>
	{else}
    <li><a href="{link this, 'page' => $step}">{$step}</a></li>
	{/if}
  {if $iterator->nextValue > $step + 1}<li><span>…</span></li>{/if}
	{/foreach}

	{if $paginator->isLast()}
    <li>
      <span>
        <span aria-hidden="true">Nasledujúca &raquo;</span>
      </span>
    </li>
	{else}
    <li>
      <a href="{link this, 'page' => $paginator->page + 1}" aria-label="Next">
        <span aria-hidden="true">Nasledujúca &raquo;</span>
      </a>
    </li>
	{/if}
  </ul>
</nav>